"""tambah modul submateri checkpoint

Revision ID: 6875b0ce261c
Revises: 
Create Date: 2026-07-29 23:00:47.739942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6875b0ce261c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('read_content', sa.Text(), nullable=False),
    sa.Column('tts_text', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('visual_type', sa.String(length=50), nullable=True),
    sa.Column('visual_data', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sub_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sub_materials_material_id'), ['material_id'], unique=False)

    op.create_table('checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submaterial_id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('answer_json', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('correct_feedback', sa.Text(), nullable=True),
    sa.Column('wrong_feedback', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submaterial_id'], ['sub_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkpoints_submaterial_id'), ['submaterial_id'], unique=False)

    op.create_table('user_submaterial_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('submaterial_id', sa.Integer(), nullable=False),
    sa.Column('selected_mode', sa.String(length=20), nullable=True),
    sa.Column('mode_completed', sa.Boolean(), nullable=False),
    sa.Column('checkpoint_completed', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('first_opened_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submaterial_id'], ['sub_materials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'submaterial_id', name='uq_user_submaterial_progress')
    )
    with op.batch_alter_table('user_submaterial_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_submaterial_progress_submaterial_id'), ['submaterial_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_submaterial_progress_user_id'), ['user_id'], unique=False)

    op.create_table('user_checkpoint_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_id', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('last_answer_json', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'checkpoint_id', name='uq_user_checkpoint_progress')
    )
    with op.batch_alter_table('user_checkpoint_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_checkpoint_progress_checkpoint_id'), ['checkpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_checkpoint_progress_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('module_order', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('short_description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_required', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('explanation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('explanation')

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('is_published')
        batch_op.drop_column('is_required')
        batch_op.drop_column('short_description')
        batch_op.drop_column('module_order')
        batch_op.drop_column('level')

    with op.batch_alter_table('user_checkpoint_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_checkpoint_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_checkpoint_progress_checkpoint_id'))

    op.drop_table('user_checkpoint_progress')
    with op.batch_alter_table('user_submaterial_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_submaterial_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_submaterial_progress_submaterial_id'))

    op.drop_table('user_submaterial_progress')
    with op.batch_alter_table('checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkpoints_submaterial_id'))

    op.drop_table('checkpoints')
    with op.batch_alter_table('sub_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sub_materials_material_id'))

    op.drop_table('sub_materials')
    # ### end Alembic commands ###
