"""tambah fitur gacha dengan server default

Revision ID: b8a87b071ca0
Revises: 6875b0ce261c
Create Date: 2026-09-01 16:07:48.112648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a87b071ca0'
down_revision = '6875b0ce261c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gacha_tickets', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('shards', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('shards')
        batch_op.drop_column('gacha_tickets')

    # ### end Alembic commands ###
